Add components
microhass/book-store pull request #1
Opened 2023-07-11 15:05 UTC by hassanShakur

- Added 2 routes in the application, each rendering a page component: `/` and `/categories`.
- Create components inside of the /components directory, having the following:
   I. Contains individual book states, as well as a button to delete the book
   ii. Contains a list to render individual books
   iii. Contains a form to create new books
   iv. Contains navigation to link to the 2 routes you created

2023-07-11 16:28 UTC, Davidosky007 requested changes
Hi @hassanShakur 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* React router used properly 👍 
* React components created properly 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 16:28 UTC, Davidosky007 commented on src/components/Book.js
>        </div>
* I strongly suggest you that you create a parent component that would house `Book` , `Booklist`, and `CreateBook` component. and in your `Book` component it 👇 
 ```
Takes the book data as a prop and renders the title and the author
Has a button for removing books
the button wouldn't remove the books yet, this is just a placeholder for now` this way its easy to render individual books with their info rather than hard coding them

2023-07-11 16:28 UTC, Davidosky007 commented on src/components/CreateBook.js
> +    // if (bookTitle.trim() === '' || bookAuthor.trim() === '') return;
* Kindly remove all commented code from your codebase as it makes your codebase bulky and unprofessional

2023-07-12 14:56 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @hassanShakur👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 15:42 UTC, merged